### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by pradeep-k**

### CODE REVIEW

**Comment by pradeep-k** [comment]
@phil-lopreiato : please merge this.

**Comment by phil-lopreiato** [comment]
LGTM :+1:

**Comment by twood02** [comment]
@phil-lopreiato - does this also need to be merged into server-dev?

**Comment by phil-lopreiato** [comment]
That's probably a good idea. It doesn't merge cleanly, though. @pradeep-k can you resolve conflicts and submit another PR from your branch against server-dev?

**Comment by pradeep-k** [comment]
I think u just gave to overwrite all the 3 files... Let me know if I need
to raise a pull request..

**Comment by phil-lopreiato** [comment]
Okay, I can merge and overwite the files. 

I'll make a PR for it though, so you can look it over and make sure it's good before I merge.

**Pull request merged**
