### PR TITLE
add test file for marshal

### PR DESCRIPTION
**Pull request by Grace-Liu**
Test file for gwkv_marshal_client(), gwkv_marshal_server(), gwkv_demarshal_server(), gwkv_demarshal_client() function.

### CODE REVIEW

**Comment by phil-lopreiato** [comment]
Please provide a description of what the tests actually do (comment here - I don't want have to read your code to know what it does)

**Comment by phil-lopreiato** [comment]
Furthermore, the tests do not appear to work. See the details at https://travis-ci.org/gwAdvNet2015/gw-kv-store/builds/59434897#L306

You can run `make && make test` locally to ensure that the test cases you've written pass before pushing them.

**Comment by Grace-Liu** [comment]
the failure is because of gwkv_demarshal_server() has been implemented, I
think my code is right and our group leader asks me to create a pull
request, so I think someone may need it to test their code.

**Comment by phil-lopreiato** [comment]
Okay then, we're going to have to work out these issues.

I tried locally merging #47 into this and seeing if that fixed, and it did not (same error).

@akorzan (I'm guessing this is your jurisdiction) please work with @Grace-Liu to find the root cause of these issues. I pushed the test code to a [new branch](https://github.com/gwAdvNet2015/gw-kv-store/tree/marshal-tests) to make it easier for you to test `gwkv_demarshal_server` and fix it.

You can run  `git pull upstream marshal-tests` to merge the tests into your working copy.

**Comment by amygara** [comment]
@phil-lopreiato @Grace-Liu Did #55 implement and resolve this and should this be closed?

**Comment by phil-lopreiato** [comment]
I think this is covered by #55 and can be closed. @Grace-Liu can you confirm?

**Comment by pradeep-k** [comment]
The tests had some issues as well. After the submit #55, things are resolved. 
Tag me or create a new issue if you see any bugs.

**Comment by phil-lopreiato** [comment]
Okay, we'll go with #55. Closing this

**Pull request closed without merging**
