### PR TITLE
Update marshal.c

### PR DESCRIPTION
**Pull request by huyang1988**

### CODE REVIEW

**Comment by phil-lopreiato** [comment]
Can you describe what this does, please?

**Comment by phil-lopreiato** [comment]
And how does this relate to #47?

**Comment by huyang1988** [comment]
actually this is the yesterday's latest version, however it seams that we did not merge it successfully. that description should be here.

**Comment by phil-lopreiato** [comment]
#47 has not been merged yet because @atryus had a couple questions we wanted to clear up before we merged.

Can you please describe what the changes you made are, and close any pull requests that are no longer needed?

**Comment by phil-lopreiato** [comment]
It appears this is the exact same as #47. Please answer the questions there and fix any comments that were pointed out. 

I'm closing this PR as a duplicate.

**Pull request closed without merging**
